/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum170625;

/**
 *
 * @author Jasminee
 */
public class Makanan extends javax.swing.JFrame {

    /**
     * Creates new form Makanan
     */
    private MenuUtama utama;
    
    
    public Makanan() {
        initComponents();
    }
    
    public Makanan(MenuUtama utama){
        this.utama = utama;
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        chknasgor = new javax.swing.JCheckBox();
        chkmie = new javax.swing.JCheckBox();
        chksate = new javax.swing.JCheckBox();
        chksoto = new javax.swing.JCheckBox();
        cbnasgor = new javax.swing.JComboBox<>();
        cbmie = new javax.swing.JComboBox<>();
        cbsate = new javax.swing.JComboBox<>();
        cbsoto = new javax.swing.JComboBox<>();
        txtnasgor = new javax.swing.JTextField();
        txtmie = new javax.swing.JTextField();
        txtsate = new javax.swing.JTextField();
        txtsoto = new javax.swing.JTextField();
        txttotnasgor = new javax.swing.JTextField();
        txttotmie = new javax.swing.JTextField();
        txttotsate = new javax.swing.JTextField();
        txttotsoto = new javax.swing.JTextField();
        btnkembali = new javax.swing.JButton();
        txttot = new javax.swing.JTextField();
        btnTotal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("MENU MAKANAN");

        chknasgor.setText("Nasi Goreng");
        chknasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chknasgorActionPerformed(evt);
            }
        });

        chkmie.setText("Mie Goreng");
        chkmie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkmieActionPerformed(evt);
            }
        });

        chksate.setText("Sate");
        chksate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chksateActionPerformed(evt);
            }
        });

        chksoto.setText("Soto");
        chksoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chksotoActionPerformed(evt);
            }
        });

        cbnasgor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        cbnasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnasgorActionPerformed(evt);
            }
        });

        cbmie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbmie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmieActionPerformed(evt);
            }
        });

        cbsate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbsate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsateActionPerformed(evt);
            }
        });

        cbsoto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbsoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsotoActionPerformed(evt);
            }
        });

        txtnasgor.setText("0");
        txtnasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnasgorActionPerformed(evt);
            }
        });

        txtmie.setText("0");

        txtsate.setText("0");

        txtsoto.setText("0");
        txtsoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsotoActionPerformed(evt);
            }
        });

        txttotnasgor.setText("0");

        txttotmie.setText("0");
        txttotmie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotmieActionPerformed(evt);
            }
        });

        txttotsate.setText("0");

        txttotsoto.setText("0");

        btnkembali.setText("Kembali Ke Menu Utama");
        btnkembali.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });

        txttot.setText("0");

        btnTotal.setText("Total");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel1)
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkmie, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                            .addComponent(chksate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chksoto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chknasgor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtsate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbsate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtmie, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbmie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtnasgor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbnasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtsoto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbsoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTotal)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txttotsate)
                    .addComponent(txttotmie)
                    .addComponent(txttotnasgor)
                    .addComponent(txttotsoto)
                    .addComponent(txttot, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chknasgor)
                    .addComponent(cbnasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttotnasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkmie)
                    .addComponent(cbmie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttotmie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chksate)
                    .addComponent(cbsate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttotsate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chksoto)
                    .addComponent(txtsoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbsoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttotsoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnkembali)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnasgorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnasgorActionPerformed

    private void txtsotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsotoActionPerformed

    private void txttotmieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotmieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotmieActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
       double nasgor = Double.parseDouble(txttotnasgor.getText());
       double mie = Double.parseDouble(txttotmie.getText());
       double sate = Double.parseDouble(txttotsate.getText());
       double soto = Double.parseDouble(txtsoto.getText());
       double total = nasgor + mie + sate + soto ;
       txttot.setText(String.valueOf(total));
       
       
    }//GEN-LAST:event_btnTotalActionPerformed

    private void chknasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chknasgorActionPerformed
        txtnasgor.setText("15000");
    }//GEN-LAST:event_chknasgorActionPerformed

    private void chkmieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkmieActionPerformed
        txtmie.setText("13000");
    }//GEN-LAST:event_chkmieActionPerformed

    private void chksateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chksateActionPerformed
       txtsate.setText("18000");
    }//GEN-LAST:event_chksateActionPerformed

    private void cbnasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnasgorActionPerformed
        int jml = (int)cbnasgor.getSelectedIndex();
        double harga = (int) Double.parseDouble(txtnasgor.getText());
        double total = jml*harga;
        txttotnasgor.setText(Double.toString(total));
        
        
    }//GEN-LAST:event_cbnasgorActionPerformed

    private void cbmieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmieActionPerformed
        int jml = (int)cbmie.getSelectedIndex();
        double harga = (int) Double.parseDouble(txtmie.getText());
        double total = jml*harga;
        txttotmie.setText(Double.toString(total));
        
    }//GEN-LAST:event_cbmieActionPerformed

    private void cbsateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsateActionPerformed
         int jml = (int)cbsate.getSelectedIndex();
        double harga = (int) Double.parseDouble(txtsate.getText());
        double total = jml*harga;
        txttotsate.setText(Double.toString(total));
        
    }//GEN-LAST:event_cbsateActionPerformed

    private void cbsotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsotoActionPerformed
        int jml = (int)cbsoto.getSelectedIndex();
        double harga = (int) Double.parseDouble(txtsoto.getText());
        double total = jml*harga;
        txttotsoto.setText(Double.toString(total));
        
    }//GEN-LAST:event_cbsotoActionPerformed

    private void chksotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chksotoActionPerformed
        txtsoto.setText("14000");
    }//GEN-LAST:event_chksotoActionPerformed

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
     String  total = txttot.getText();
     utama.setTotalMakanan(total);
     this.dispose();
    
    }//GEN-LAST:event_btnkembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Makanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Makanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Makanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Makanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Makanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTotal;
    private javax.swing.JButton btnkembali;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbmie;
    private javax.swing.JComboBox<String> cbnasgor;
    private javax.swing.JComboBox<String> cbsate;
    private javax.swing.JComboBox<String> cbsoto;
    private javax.swing.JCheckBox chkmie;
    private javax.swing.JCheckBox chknasgor;
    private javax.swing.JCheckBox chksate;
    private javax.swing.JCheckBox chksoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtmie;
    private javax.swing.JTextField txtnasgor;
    private javax.swing.JTextField txtsate;
    private javax.swing.JTextField txtsoto;
    private javax.swing.JTextField txttot;
    private javax.swing.JTextField txttotmie;
    private javax.swing.JTextField txttotnasgor;
    private javax.swing.JTextField txttotsate;
    private javax.swing.JTextField txttotsoto;
    // End of variables declaration//GEN-END:variables
}
