/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum170625;

/**
 *
 * @author Jasminee
 */
public class Minuman extends javax.swing.JFrame {

    /**
     * Creates new form Minuman
     */
    public Minuman() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chkmilk = new javax.swing.JCheckBox();
        chkesteller = new javax.swing.JCheckBox();
        chkthaitea = new javax.swing.JCheckBox();
        chkcapucino = new javax.swing.JCheckBox();
        txtmilk = new javax.swing.JTextField();
        txtesteller = new javax.swing.JTextField();
        txtthaitea = new javax.swing.JTextField();
        txtcapucino = new javax.swing.JTextField();
        cbmilk = new javax.swing.JComboBox<>();
        cbesteller = new javax.swing.JComboBox<>();
        cbthaitea = new javax.swing.JComboBox<>();
        cbcapucino = new javax.swing.JComboBox<>();
        txttotmilk = new javax.swing.JTextField();
        txttotesteller = new javax.swing.JTextField();
        txttotthaitea = new javax.swing.JTextField();
        txttotcapucino = new javax.swing.JTextField();
        btntotal = new javax.swing.JButton();
        txttotal = new javax.swing.JTextField();
        btnkembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Menu Minuman");

        chkmilk.setText("Milk Shake");
        chkmilk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkmilkActionPerformed(evt);
            }
        });

        chkesteller.setText("Es Teller");
        chkesteller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkestellerActionPerformed(evt);
            }
        });

        chkthaitea.setText("Thai Tea");
        chkthaitea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkthaiteaActionPerformed(evt);
            }
        });

        chkcapucino.setText("Capucino");
        chkcapucino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkcapucinoActionPerformed(evt);
            }
        });

        txtmilk.setText("0");

        txtesteller.setText("0");

        txtthaitea.setText("0");

        txtcapucino.setText("0");

        cbmilk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        cbmilk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmilkActionPerformed(evt);
            }
        });

        cbesteller.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        cbesteller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbestellerActionPerformed(evt);
            }
        });

        cbthaitea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbthaitea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbthaiteaActionPerformed(evt);
            }
        });

        cbcapucino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbcapucino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcapucinoActionPerformed(evt);
            }
        });

        txttotmilk.setText("0");

        txttotesteller.setText("0");

        txttotthaitea.setText("0");

        txttotcapucino.setText("0");

        btntotal.setText("Total");

        txttotal.setText("0");

        btnkembali.setText("Kembali ke Menu Utama");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chkesteller, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkmilk, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkthaitea, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkcapucino, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmilk, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtesteller, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtthaitea, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcapucino, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbesteller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbmilk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbthaitea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(113, 113, 113)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txttotesteller, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                        .addComponent(txttotmilk)
                                        .addComponent(txttotthaitea)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbcapucino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btntotal))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txttotcapucino)
                                        .addComponent(txttotal)
                                        .addComponent(btnkembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkmilk)
                    .addComponent(txtmilk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbmilk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttotmilk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkesteller)
                    .addComponent(txtesteller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbesteller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttotesteller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbthaitea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttotthaitea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtthaitea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkthaitea))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkcapucino)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtcapucino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbcapucino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txttotcapucino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntotal)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnkembali)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkmilkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkmilkActionPerformed
       txtmilk.setText("20000");
    }//GEN-LAST:event_chkmilkActionPerformed

    private void chkestellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkestellerActionPerformed
       txtesteller.setText("7000");
    }//GEN-LAST:event_chkestellerActionPerformed

    private void chkthaiteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkthaiteaActionPerformed
        txtthaitea.setText("12000");
    }//GEN-LAST:event_chkthaiteaActionPerformed

    private void chkcapucinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkcapucinoActionPerformed
        txtmilk.setText("8000");
    }//GEN-LAST:event_chkcapucinoActionPerformed

    private void cbmilkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmilkActionPerformed
        int jml = (int)cbmilk.getSelectedIndex();
        double harga = (int) Double.parseDouble(txtmilk.getText());
        double total = jml*harga;
        txttotmilk.setText(Double.toString(total));
    }//GEN-LAST:event_cbmilkActionPerformed

    private void cbestellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbestellerActionPerformed
        int jml = (int)cbesteller.getSelectedIndex();
        double harga = (int) Double.parseDouble(txtesteller.getText());
        double total = jml*harga;
        txttotesteller.setText(Double.toString(total));
    }//GEN-LAST:event_cbestellerActionPerformed

    private void cbthaiteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbthaiteaActionPerformed
        int jml = (int)cbthaitea.getSelectedIndex();
        double harga = (int) Double.parseDouble(txtthaitea.getText());
        double total = jml*harga;
        txttotthaitea.setText(Double.toString(total));
    }//GEN-LAST:event_cbthaiteaActionPerformed

    private void cbcapucinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcapucinoActionPerformed
        int jml = (int)cbcapucino.getSelectedIndex();
        double harga = (int) Double.parseDouble(txtcapucino.getText());
        double total = jml*harga;
        txttotcapucino.setText(Double.toString(total));
    }//GEN-LAST:event_cbcapucinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Minuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Minuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Minuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Minuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Minuman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btntotal;
    private javax.swing.JComboBox<String> cbcapucino;
    private javax.swing.JComboBox<String> cbesteller;
    private javax.swing.JComboBox<String> cbmilk;
    private javax.swing.JComboBox<String> cbthaitea;
    private javax.swing.JCheckBox chkcapucino;
    private javax.swing.JCheckBox chkesteller;
    private javax.swing.JCheckBox chkmilk;
    private javax.swing.JCheckBox chkthaitea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtcapucino;
    private javax.swing.JTextField txtesteller;
    private javax.swing.JTextField txtmilk;
    private javax.swing.JTextField txtthaitea;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txttotcapucino;
    private javax.swing.JTextField txttotesteller;
    private javax.swing.JTextField txttotmilk;
    private javax.swing.JTextField txttotthaitea;
    // End of variables declaration//GEN-END:variables
}
